services:
    loevgaard_dandomain_sort_helper.helper:
        class: Loevgaard\DandomainSortHelperBundle\Helper\Helper
        calls:
            - [setContainer, ['@service_container']]

    loevgaard_dandomain_sort_helper.twig_extension:
            class: Loevgaard\DandomainSortHelperBundle\Twig\DandomainSortExtension
            arguments:
                - "@loevgaard_dandomain_sort_helper.helper"
            public: false
            tags:
                - { name: twig.extension }